// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['WailsApp']['CopyToClipboard'](arg1);
}

export function CreateGame(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WailsApp']['CreateGame'](arg1, arg2, arg3, arg4);
}

export function GameList() {
  return window['go']['main']['WailsApp']['GameList']();
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function GetState() {
  return window['go']['main']['WailsApp']['GetState']();
}

export function HideWindow() {
  return window['go']['main']['WailsApp']['HideWindow']();
}

export function JoinGame(arg1, arg2, arg3) {
  return window['go']['main']['WailsApp']['JoinGame'](arg1, arg2, arg3);
}

export function LeaveGame() {
  return window['go']['main']['WailsApp']['LeaveGame']();
}

export function RefreshAllStates() {
  return window['go']['main']['WailsApp']['RefreshAllStates']();
}

export function RefreshState() {
  return window['go']['main']['WailsApp']['RefreshState']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['WailsApp']['SaveSettings'](arg1, arg2);
}

export function SelectWatchDir() {
  return window['go']['main']['WailsApp']['SelectWatchDir']();
}

export function SetTurnOrder(arg1) {
  return window['go']['main']['WailsApp']['SetTurnOrder'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['WailsApp']['ShowWindow']();
}

export function StartGame() {
  return window['go']['main']['WailsApp']['StartGame']();
}

export function StatusText() {
  return window['go']['main']['WailsApp']['StatusText']();
}

export function SwitchGame(arg1) {
  return window['go']['main']['WailsApp']['SwitchGame'](arg1);
}
