// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.CreateGameResponse>;

export function GameList():Promise<Array<config.GameConfig>>;

export function GetConfig():Promise<config.ClientConfig>;

export function GetState():Promise<models.GameState>;

export function HideWindow():Promise<void>;

export function JoinGame(arg1:string,arg2:string,arg3:string):Promise<models.JoinResponse>;

export function LeaveGame():Promise<void>;

export function RefreshAllStates():Promise<Record<string, models.GameState>>;

export function RefreshState():Promise<models.GameState>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SelectWatchDir():Promise<string>;

export function SetTurnOrder(arg1:Array<string>):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartGame():Promise<void>;

export function StatusText():Promise<string>;

export function SwitchGame(arg1:string):Promise<Array<config.GameConfig>>;
